-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 23:25:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema eatsoon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eatsoon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eatsoon` DEFAULT CHARACTER SET utf8mb4 ;
USE `eatsoon` ;

-- -----------------------------------------------------
-- Table `eatsoon`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eatsoon`.`producto` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_publicacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `nombre_producto` VARCHAR(45) NOT NULL,
  `precio_producto` VARCHAR(45) NOT NULL,
  `fecha_caducidad` DATE NOT NULL,
  `desc_producto` VARCHAR(500) NOT NULL,
  `cantidad` INT(10) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `pedido_codPedido` INT NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `eatsoon`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eatsoon`.`usuario` (
  `CI` INT(11) NOT NULL,
  `NOMBRE` VARCHAR(20) NOT NULL,
  `APELLIDO` VARCHAR(20) NOT NULL,
  `DIRECCION` VARCHAR(50) NOT NULL,
  `TELEFONO` INT(11) NOT NULL,
  `CORREO` VARCHAR(30) NOT NULL,
  `CONTRASEÑA` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`CI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `eatsoon`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eatsoon`.`pedido` (
  `codPedido` INT NOT NULL,
  `producto_id_producto` INT(11) NOT NULL,
  `usuario_CI` INT(11) NOT NULL,
  `tatal_Pedido` INT NOT NULL,
  `fecha_Pedido` INT NOT NULL,
  PRIMARY KEY (`codPedido`),
  INDEX `fk_pedido_producto_idx` (`producto_id_producto` ASC) VISIBLE,
  INDEX `fk_pedido_usuario1_idx` (`usuario_CI` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_producto`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `eatsoon`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`usuario_CI`)
    REFERENCES `eatsoon`.`usuario` (`CI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
